<a href="https://colab.research.google.com/github/Hariom-byte/Data-Analytics/blob/main/Final_NumPy_Assignment_Classes_1_to_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final NumPy Assignment (Classes 1–4)

### Instructions
- Solve all questions.
- Write your code in the code cell below each question.
- Do not modify the questions.
- Total Questions: **30**


# Part A – Array Creation

### Q1. Create a NumPy array from the list `[5,10,15,20,25]`.

In [ ]:
import numpy as np
l = [5,10,15,20,25]
arr = np.array(l)
print(arr)


[ 5 10 15 20 25]


### Q2. Create a **3×4** array of zeros.

In [ ]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Q3. Create a **4×4** array of ones.

In [ ]:
np.ones((4,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Q4. Create a **5×5 identity matrix** using `np.eye()`.

In [ ]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Q5. Create an array from **1 to 50** with a step of **5**.

In [ ]:
arr = np.arange(1,50,5)
print(arr)


[ 1  6 11 16 21 26 31 36 41 46]


# Part B – Array Attributes

### Q6. Find the **shape** of the given array.

In [ ]:
arr = np.arange(1, 51, 5)
print(arr)
print(arr.shape)


[ 1  6 11 16 21 26 31 36 41 46]
(10,)


### Q7. Find the **number of dimensions (`ndim`)**.

In [ ]:
arr.ndim

1

### Q8. Find the **total number of elements (`size`)**.

In [ ]:
arr.size


10

### Q9. Find the **data type (`dtype`)**.

In [ ]:
arr.dtype


dtype('int64')

### Q10. Convert the array into **float** datatype.

In [ ]:
float_arr = arr.astype(float)
print(float_arr)


[ 1.  6. 11. 16. 21. 26. 31. 36. 41. 46.]


# Part C – Indexing & Slicing

### Q11. Print the **first element** of a 1D array.

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[0])


1


### Q12. Print the **last element** of a 1D array.

In [ ]:
print(arr[-1])


5


### Q13. Print the **first row** of a 2D array.

In [ ]:
matrix = ([[1,2,3],[4,5,6]])
print(matrix[0])


[1, 2, 3]


### Q14. Print the **last column** of a 2D array.

In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[:, -1])

[3 6 9]


### Q15. Print elements from **index 2 to 7**.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2:8])


[3 4 5 6 7 8]


### Q16. Reverse the array using slicing.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1])


[10  9  8  7  6  5  4  3  2  1]


# Part D – Reshape & Flatten

### Q17. Convert a 1D array of **12 elements** into a **3×4** matrix.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrix = arr.reshape(3,4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q18. Reshape the above matrix into **2×6**.

In [ ]:
matrix = matrix.reshape(2,6)
print(matrix)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### Q19. Flatten the matrix using `flatten()`.

In [ ]:
arr = matrix.flatten()
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


### Q20. Reshape the array into **4×3**.

In [ ]:
arr = arr.reshape(4,3)
print(arr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Part E – Broadcasting & Arithmetic

### Q21. Add **10** to every element of an array.

In [ ]:
print(arr+10)


[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


### Q22. Multiply every element by **5**.

In [ ]:
print(arr*5)


[[ 5 10 15]
 [20 25 30]
 [35 40 45]
 [50 55 60]]


### Q23. Add two arrays element-wise.

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)


[ 7  9 11 13 15]


### Q24. Find the square of every element.

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr**2)


[ 1  4  9 16 25]


# Part F – Fancy & Boolean Indexing

### Q25. Using fancy indexing, print **20, 40, 80** from a 1D array.

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[[1,3,7]])


[20 40 80]


### Q26. Using fancy indexing, print the **first and third rows** of a 2D array.

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[[0,2]])


[[1 2 3]
 [7 8 9]]


### Q27. Using boolean indexing, print elements **greater than 20**.

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print([arr>20])


[array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])]


### Q28. Using boolean indexing, print only the **even numbers**.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr%2==0)


[False  True False  True False  True False  True False  True]


# Part G – Sorting & Concatenation

### Q29. Sort an array using `np.sort()`.

In [ ]:
arr = np.array([6,52,3,1,2,7,67,34,12])
print(np.sort(arr))


[ 1  2  3  6  7 12 34 52 67]


### Q30. Find the sorted indices using `np.argsort()`.

In [ ]:
arr = np.array([6,52,3,1,2,7,67,34,12])
print(np.argsort(arr))


[3 4 2 0 5 8 7 1 6]


### Q31. Join two arrays using `np.concatenate()`.

In [ ]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.concatenate((arr,arr2)))


[1 2 3 4 5 6 7 8]
