
# NumPy Assignment — Array Attributes, Indexing & Slicing



# Q1. Array Attributes

## Problem Statement
Create the following NumPy array:

```python
[10, 20, 30, 40, 50]
```

Print:
- Shape
- Number of Dimensions
- Size
- Data Type

## Sample Output
```python
Shape: (5,)
Dimensions: 1
Size: 5
dtype: int64
```


In [ ]:
import numpy as np
l = [10,20,30,40,50]
arr = np.array(l)
print(f"shape:{arr.shape}")
print(f"Dimensions:,{arr.ndim}")
print(f"size:{arr.size}")
print(f"dtype:{arr.dtype}")


# Q2. Find Array Shape

## Problem Statement
Create the following array:

```python
[[1,2,3],
 [4,5,6]]
```

Print only the shape of the array.

## Sample Output
```python
(2, 3)
```


In [ ]:
matrix =([[1,2,3],[4,5,6]])
arr = np.array(matrix)
print(arr.shape)


# Q3. 1D Indexing

## Problem Statement
Create the array:

```python
[5, 10, 15, 20, 25]
```

Print:
- First element
- Last element

## Sample Output
```python
5
25
```


In [ ]:
l = [5,10,15,20,25]
arr = np.array(l)
print(arr[0])
print(arr[-1])


# Q4. 2D Indexing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the element `50`.

## Sample Output
```python
50
```


In [ ]:
matrix = ([[10,20,30],[40,50,60],[70,80,90]])
arr = np.array(matrix)
print(arr[1,1])


# Q5. 2D Indexing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the element `9`.

## Sample Output
```python
9
```


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr[2,2])


# Q6. 1D Slicing

## Problem Statement
Create the array:

```python
[10,20,30,40,50,60]
```

Print elements from index 1 to 4.

## Sample Output
```python
[20 30 40 50]
```


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(arr[1:5])



# Q7. 1D Slicing

## Problem Statement
Create the array:

```python
[1,2,3,4,5,6,7,8]
```

Print the first 5 elements.

## Sample Output
```python
[1 2 3 4 5]
```


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[:5])


# Q8. 2D Slicing

## Problem Statement
Create the array:

```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

Print the first two rows.

## Sample Output
```python
[[1 2 3]
 [4 5 6]]
```


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])


print(arr[:2])


# Q9. 2D Slicing

## Problem Statement
Create the array:

```python
[[10,20,30],
 [40,50,60],
 [70,80,90]]
```

Print the first two columns of all rows.

## Sample Output
```python
[[10 20]
 [40 50]
 [70 80]]
```


In [ ]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
print(arr[:, :2])

# Q10. `np.eye()`

## Problem Statement
Using NumPy, create a **4 × 4 identity matrix** using the `np.eye()` function.

Print the resulting matrix.

## Sample Output
```python
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
```

In [ ]:
print(np.eye(4))

### Boolean Indexing (Practice)

**Q1.** Create a NumPy array from 1 to 20. Print only the elements greater than 10 using boolean indexing.



In [ ]:
arr = np.arange(1,21)
print(arr[arr > 10])


**Q2.** Create the array:
```python
arr = np.array([12, 5, 18, 7, 25, 30, 2, 15])
```
Print only the even numbers using boolean indexing.


In [ ]:
arr = np.array([12,5,18,7,25,30,2,15])
print(arr[arr % 2 == 0])



**Q3.** Create a 4×4 random integer array (1–50). Print only the values greater than 25 using boolean indexing.


In [ ]:
arr = np.random.randint(1,51,(4,4))
print(arr[arr > 25])